### PR TITLE
Replace all uses of `var` with `const`

### PR DESCRIPTION
**Pull request by rchavarria**
PR #53 does not replace all uses of `var`. This PR completes that work. In case of merging, it should be done after merging #53.

### CODE REVIEW

**Comment by rchavarria** [comment]
@matthewmorgan Would you mind to take a look to this PR? I think it's an easy one, but I would like to have another pair of eyes to look at it and to have a second opinion about my changes. Thanks!

**Comment by matthewmorgan** [comment]
@rchavarria looks good to me.  I don't see any instances where you're trying to reassign after using ```const```, so I think you're OK.

**Comment by rchavarria** [comment]
@kytrinyx, @mixolidia Do you think this code is ready to be merged?

**Comment by kytrinyx** [comment]
Yepp, go for it.

**Comment by rchavarria** [comment]
Some time ago, @kytrinyx, you asked me for candidates to have write permissions on xecmascript and/or xjavascript repos. I think that @matthewmorgan is a perfect candidate. He's contributing a lot on xecmascript and he's very active on exercism.io on both JavaScript tracks.

**Comment by kytrinyx** [comment]
Awesome, inviting him now. Thanks!

**Comment by matthewmorgan** [comment]
@rchavarria  @kytrinyx happy to help, and it's and honor to be invited.  Eventually I'll get the hang of Git... ;)

**Comment by kytrinyx** [comment]
> Eventually I'll get the hang of Git... ;)

Won't we all!

**Pull request merged**
