### PR TITLE
Immutable gigasecond test

### PR DESCRIPTION
**Pull request by matthewmorgan**
Added a test like https://github.com/exercism/xjavascript/pull/125 for this track.

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@rchavarria here's the test for giagsecond.  Please have a look when you can.  Thanks

**Comment by rchavarria** [comment]
It looks perfect! And you replaced `let` by `const`! Awesome! Thanks.

I can't merge it right now, but I hope I can do it later today.

**Comment by matthewmorgan** [comment]
Cool.  If you have time to look at those other PRs as well, right now I
think it's just the two of us merging them, and I'm trying not to do my own
without review (as you suggested).  Thanks!


On Mon, Nov 16, 2015 at 7:19 AM, Rubén Chavarría <notifications@github.com>
wrote:

> It looks perfect! And you replaced let by const! Awesome! Thanks.
>
> I can't merge it right now, but I hope I can do it later today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/xecmascript/pull/67#issuecomment-157011351>.
>



-- 
Matt Morgan
Director of Technology
Dulcet Software LLC
(734) 926-8142

**Comment by rchavarria** [comment]
Yep, I know I've been *offline* some days. Thanks for keeping the activity.

**Comment by matthewmorgan** [comment]
Thanks and no worries.  I had the time.  Next week I will not!

On Mon, Nov 16, 2015 at 9:25 AM, Rubén Chavarría <notifications@github.com>
wrote:

> Yep, I know I've been *offline* some days. Thanks for keeping the
> activity.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/xecmascript/pull/67#issuecomment-157046043>.
>



-- 
Matt Morgan
Director of Technology
Dulcet Software LLC
(734) 926-8142

**Pull request merged**
