### PR TITLE
Add new exercise pangram

### PR DESCRIPTION
**Pull request by matthewmorgan**
As proposed in https://github.com/exercism/x-common/pull/133

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@kytrinyx hmm...no Travis check ran when I made this PR?

**Comment by kytrinyx** [comment]
It looks like the travis checks ran and passed.

**Comment by rchavarria** [comment]
Thanks a lot.

Sorry, all merged PR are shown as *Closed* today. I'm really, really sorry.

**Comment by matthewmorgan** [comment]
No worries.  Did you ever figure out if it was your ```.gitconfig```, or
what the difference might be?

On Thu, Nov 26, 2015 at 10:52 AM, Rubén Chavarría <notifications@github.com>
wrote:

> Thanks a lot.
>
> Sorry, all merged PR are shown as *Closed* today. I'm really, really
> sorry.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/xecmascript/pull/88#issuecomment-159946119>.
>



-- 
Matt Morgan
Director of Technology
Dulcet Software LLC
(734) 926-8142

**Comment by rchavarria** [comment]
Nope. I noticed that sometimes, when running the command `git fetch origin`, I sometimes get PRs as new branches, sometimes not. But I don't know yet why some merges *close* the PR instead of *merge*.

I'm sure all branches have been rebased to master before merge (with `--no-ff` option) into master.

**Pull request closed without merging**
