### PR TITLE
Add new exercise atbash-cipher

### PR DESCRIPTION
**Pull request by matthewmorgan**
As described in #92

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@rchavarria this is what I did to bring this current:

First you would need to fetch the new exercise branch, then

```
git checkout new-exercise-atbash-cipher
git checkout master
git fetch && git reset --hard origin/master
git checkout new-exercise-atbash-cipher
git rebase master
```

I fixed the conflicts in config.json, then

```
git push -f origin new-exercise-atbash-cipher
```

**Comment by matthewmorgan** [comment]
Oh, it looks like you figured that out already in #101 !!

**Comment by rchavarria** [comment]
XD 

Yes! We're learning the same thing at the same time in different places. LOL

**Comment by rchavarria** [comment]
Done! Amazing @matthewmorgan !

**Comment by matthewmorgan** [comment]
@rchavarria only 500,000 more lines and I'll be caught up to your contributions!  Thanks again for inviting me.

**Pull request merged**
