### PR TITLE
Fix gulpfile errors WRT eslint

### PR DESCRIPTION
**Pull request by matthewmorgan**
@rchavarria I missed a couple of dangling commas in your PR #175.  This is causing annoying lint errors when trying to test exercises!

My bad, I fixed it and I'm going to merge so it doesn't cause the users hassles!

### CODE REVIEW

**Comment by rchavarria** [comment]
Whoops. I didn't realize them. Thank you.

I'm also was thinking about this: currently, `gulpfile` forces users to lint their code if they want to run tests. For some users, this can be annoying, or even frustrating. They're getting errors, not related to tests, and they may not understand them.

I propose to make the `test` task independent from the `lint` task. During development and in Travis CI, we must run the command `gulp lint` and `gulp test` (maybe `gulp lint test` works) to both lint the code and run the tests. 

It would also be added to the README file of the track, so that users will know about the feature. But their code won't be always linted.

**Comment by matthewmorgan** [comment]
I can see the logic in breaking it out into a separate task.   I'm of a divided mind: I feel like it's good to encourage best practices by making the linting automatic, but I am wondering if there is a precedent for this with other tracks.  I wonder if @kytrinyx could shine some light on this.

**Comment by kytrinyx** [comment]
I think we should separate it. I am all about encouraging best practices, but we can do that with the README (and the comments on the site, as well). I think it's useful when starting out in a new language to not have everything done for you automatically.

**Comment by matthewmorgan** [comment]
Ok, sounds good.  @rchavarria did you want to take on this task?  If not, I think I can figure it out.

**Comment by rchavarria** [comment]
I don't have too much spare time this week, sorry. You can do it if you don't mind, but don't feel you must do it. I could spend some time in a couple of days.

**Comment by matthewmorgan** [comment]
I might have some time this weekend.  The family is coming over for
Christmas today, but if I can get to it later I will.

I suppose it's a holiday there too: have a good one!


On Fri, Dec 25, 2015 at 7:10 AM, Rubén Chavarría <notifications@github.com>
wrote:

> I don't have too much spare time this week, sorry. You can do it if you
> don't mind, but don't feel you must do it. I could spend some time in a
> couple of days.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/xecmascript/pull/179#issuecomment-167225808>.
>



-- 
Matt Morgan
Director of Technology
Dulcet Software LLC
(734) 926-8142

**Pull request merged**
