### PR TITLE
Fix lint issue in Grains by segregating library code

### LINKED ISSUE #220: Grains: the provided BigInt implementation fails linter
Running `npm test` with an empty `grains.js` implementation yields:

```shell
~/exercism/ecmascript/grains$ npm test

> xecmascript@0.0.0 test /home/ryan/exercism/ecmascript/grains
> gulp lint test

[20:17:28] Using gulpfile ~/exercism/ecmascript/grains/gulpfile.js
[20:17:28] Starting 'lint'...
[20:17:28] Starting 'babel'...
[20:17:29] 
big-integer.js
   260:18  error  Move variable declaration to function body root  no-inner-declarations
   366:18  error  Move variable declaration to function body root  no-inner-declarations
   505:13  error  Move variable declaration to function body root  no-inner-declarations
   509:17  error  Move variable declaration to function body root  no-inner-declarations
   576:13  error  Unexpected assignment within an 'if' statement   no-cond-assign
   581:9   error  Unexpected constant condition                    no-constant-condition
   614:14  error  Move variable declaration to function body root  no-inner-declarations
   754:6   error  Unnecessary semicolon                            no-extra-semi
   784:14  error  Move variable declaration to function body root  no-inner-declarations
   785:13  error  Move variable declaration to function body root  no-inner-declarations
   823:16  error  Gratuitous parentheses around expression         no-extra-parens
   824:13  error  Gratuitous parentheses around expression         no-extra-parens
   890:14  error  Move variable declaration to function body root  no-inner-declarations
   961:14  error  Move variable declaration to function body root  no-inner-declarations
   962:13  error  Move variable declaration to function body root  no-inner-declarations
   963:13  error  Move variable declaration to function body root  no-inner-declarations
   983:13  error  Move variable declaration to function body root  no-inner-declarations
   988:17  error  Move variable declaration to function body root  no-inner-declarations
  1035:13  error  Move variable declaration to function body root  no-inner-declarations
  1075:17  error  Move variable declaration to function body root  no-inner-declarations
  1085:17  error  Move variable declaration to function body root  no-inner-declarations
  1089:17  error  Move variable declaration to function body root  no-inner-declarations
  1090:17  error  Move variable declaration to function body root  no-inner-declarations
  1132:10  error  Move variable declaration to function body root  no-inner-declarations

✖ 24 problems (24 errors, 0 warnings)

[20:17:29] 'lint' errored after 1.06 s
[20:17:29] ESLintError in plugin 'gulp-eslint'
Message:
    Failed with 24 errors
[20:17:29] Finished 'babel' after 1.01 s
npm ERR! Test failed.  See above for more details.
```

I needed to modify `package.json` to omit lint from the test script in order to run `npm test` successfully.

### PR DESCRIPTION
**Pull request by ryanplusplus**
Closes #220 

@rchavarria this is a bit different than what you suggested, but it retains linting on everything that isn't library code. Please let me know what you think.

### CODE REVIEW

**Comment by rchavarria** [comment]
Hmmm. I see your point. Looks reasonable, but Travis CI [fails](https://travis-ci.org/exercism/xecmascript/builds/127356079) when running all tests:

    $ make test
    cp: cannot stat `exercises/grains/big-integer.js': No such file or directory
    make[1]: *** [test-assignment] Error 1
    make: *** [test] Error 1

It seems you need to update [`Makefile`](https://github.com/exercism/xecmascript/blob/master/Makefile), line 26, to fix the path to `big-integer.js`. You would probably need to update also `big-integer.spec.js` and `example.js` (both line 1) to be able to import `BigInt`.

You should be able to run `make test` locally and see whether it works fine.

**Comment by ryanplusplus** [comment]
@rchavarria my bad, didn't realize Travis had puked. I've updated things so that
- The changes to the gulpfile were moved to the master gulpfile and propagated down to each exercise's gulpfile
- The makefile now references the new location of the bigint library

**Comment by rchavarria** [comment]
It looks fine to me now. But I just realize that I'm not sure if exercism.io will fetch files under `lib` directory. Before merging this PR I would like to ask @kytrinyx:

@kytrinyx, in an exercise, if some files are placed under a directory, let's say `lib`, will the be downloaded to exercism users when they fetch the exercise? If so, @ryanplusplus's solution to a lint issue would be ok. If not, we should find a different approach.

Thanks.

**Comment by kytrinyx** [comment]
No, it will not. It's planned behavior, but I haven't started working on it.

**Comment by ryanplusplus** [comment]
Okay, I'll go back to the drawing board.

**Comment by rchavarria** [comment]
Whoops! I should have asked before :cry: 

Sorry, @ryanplusplus, `big-integer.js` file can't be placed in a subfolder within the exercise folder.

**Comment by kytrinyx** [comment]
Wait, what? I didn't realize we were talking about a subfolder inside the exercise folder. Yes, everything in subdirectories is automatically fetched.

I thought you meant a track-global lib folder.

**Comment by ryanplusplus** [comment]
Good to go then, right?

**Comment by kytrinyx** [comment]
I believe so. Would you mind rebasing onto the upstream master?

**Comment by ryanplusplus** [comment]
Done

**Comment by matthewmorgan** [comment]
@ryanplusplus not to jump in at the last minute here, but usually we like to squash all commits down to one for each PR.  Would you mind doing that, or if you want me to do it I would be happy to.  LMK.  Thanks!

**Comment by ryanplusplus** [comment]
Done

**Comment by matthewmorgan** [comment]
@ryanplusplus thanks!

**Comment by rchavarria** [comment]
Everything's good. Thanks @ryanplusplus! And thanks @kytrinyx for your support!

**Pull request merged**
