### PR TITLE
Change first test to pass undefined name

### PR DESCRIPTION
**Pull request by matthewmorgan**
Per #112

### CODE REVIEW

**Comment by rchavarria** [comment]
Now that the test has changed, what if the implementation on `example.js` is changed and it uses *optional parameters*?

exercism.io users won't see that file, but the implementation would be better.

**Comment by matthewmorgan** [comment]
Like this?  As it happens this was the implementation I was trying to suggest to my colleague that failed against the older version of the test!  And then I didn't write `example.js` that way...

**Comment by kytrinyx** [comment]
I like this.

**Comment by rchavarria** [comment]
Sorry @matthewmorgan, but `hello-world.js` file has been deleted. I think it's important to keep it in this very first exercise, to help users to get started as fast as possible. 

I know that the provided file almost solve the problem. Maybe, if the `name` parameter is removed from the `hello()` method... It would make the exercise a little harder to solve.

**Comment by matthewmorgan** [comment]
@rchavarria I thought I had left that in by mistake, so I removed it!  Just an oversight on my part.

**Comment by rchavarria** [comment]
No problem, that's the goal of code reviews and PR.

**Comment by rchavarria** [comment]
Nice!

**Pull request merged**
