### PR TITLE
Use local jest instead of global in Makefile

### PR DESCRIPTION
**Pull request by tejasbubane**
The Makefile was relying on global installation of jest to run the
tests. This failed for me since I did not have jest globally
installed. Also the README does not mention about installing globally
which is anyways not a good idea (might cause issues due to different versions).

Hence, change Makefile to use locally installed jest instead.

### CODE REVIEW

**Comment by tejasbubane** [comment]
Looks like travis does not recognize `./node_modules` path 😞

**Comment by matthewmorgan** [comment]
@tejasbubane I think your directory path is wrong.  This works for me:

```bash
@./node_modules/.bin/jest $(OUTDIR)/temp.*.spec.js
```
Since I can't push to your fork, want to give that a try?

**Comment by tejasbubane** [comment]
Travis was not happy with the `./` in the beginning. Removing that worked 😄 .

> @./node_modules/.bin/jest $(OUTDIR)/temp.*.spec.js

I forgot node_modules creates these bins (they are just symlinks to the filepath I have given). Better to use these than to dig inside the jest-cli directory. Will change it.

**Comment by matthewmorgan** [comment]
Great!  Good to get this cleaned up.

**Comment by tejasbubane** [comment]
I also removed the `npm install` from `travis.yml` since travis will automatically do that when it finds `package.json` in project root.

**Pull request merged**
