### PR TITLE
Add new exercise: Binary search tree

### PR DESCRIPTION
**Pull request by rchavarria**
As described in #138

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@rchavarria do you want to change the `var` declarations in `example.js` to `const` or `let`?  Doesn't matter to the users of course...

**Comment by rchavarria** [comment]
Sure. I'll change them. I'd like to consider `var` *deprecated* in ES2015 code. Thanks for catching it.

**Comment by matthewmorgan** [comment]
Yes, it did make me wonder if there is some occasion where you might *want* to use `var`.  Seems like it is best avoided.

**Comment by matthewmorgan** [comment]
Thanks again!  From the 'surrealism compliment generator': 

>When faced with scathing winds and torrents pouring forth stain, your mind thinks cleverly to the leprous angels found in all train crashes

**Comment by rchavarria** [comment]
:smile: Really fun this ComplimentBot 4000

BTW Do you rebase to master before merging the branch? In the branches graph, it looks like you don't. I'm just asking.

merging

Notice first blue, yellow and purple compared to second green and second blue lines. Second ones don't start from the most recent commit.

**Comment by matthewmorgan** [comment]
No-- I guess I'm not doing it right.  I have done the last few using the merge button instead of the CLI.

This last merge (robot-simulator) I pull down your branch, rebased master, then pushed it up to exercism master, but it didn't merge-- I still had to merge the PR using the button.

**Comment by rchavarria** [comment]
Strange. It works like a charm for me with your PRs.

I'll create two new PRs later (today or tomorrow I think). Don't merge them, just comment if you agree with them and if you think they are ready to merge. I'll try to follow the same process with the as I follow with yours. We'll see whether it works or not.

**Comment by matthewmorgan** [comment]
Yeah, I just checked my notes from our conversation on #93, and the only difference I see is that I was working always on exercism, as opposed to having the PR branch be on a fork.

**Comment by matthewmorgan** [comment]
So...I'm looking at that network graph and wondering: is the issue that your branch needs to be rebased before merging?  I don't think I can rebase your fork for you.

In other words, is it working for my PRs because you're doing something different than I am with the merge or because my PR branches are on the exercism repo?

I am still pretty green with this, so it's probably me.

**Comment by rchavarria** [comment]
It's probably you're working on exercism repo. We can try also if you create some PRs from your forked repo, and I try to merge them as I've been merging your last PRs.

**Comment by matthewmorgan** [comment]
OK, I will create one and let you know.  I haven't been using my fork, so I will have to bring it up to date.  I think this means that we will have to wait for at least one other PR to be merged before merging mine to see what happens with the graph.

**Pull request merged**
