### PR TITLE
Add test to help implement Robot with smaller steps

### PR DESCRIPTION
**Pull request by rchavarria**
While practising this exercise, I miss a intermediate test from having just one robot with a name to thousands of robots with different names.

This new test tries to guide the user with smaller steps. One can first hardcode the first name. Then, the user needs to generate a different name, but only one more. After that, the next test ask the user to generate 10k different names.

### CODE REVIEW

**Comment by matthewmorgan** [comment]
Merged #62.  Thanks!

**Comment by matthewmorgan** [comment]
@kytrinyx I could use some help on this one: I merged this manually using the CLI, and the code changes are in the exercism/xecmascript repo, but the GUI doesn't show the changes as merged.  Here's the method I used, wondering if the problem is the last line:

```
$ cd <repository-name>
$ git pull
$ git remote add <username> <URL>
$ git fetch <username>
$ git checkout -b <pr-branch> <username>/<pr-branch>

(check things out, run your tests, etc.  If all is OK, proceed as below)

$ git rebase master
$ git checkout master
$ git merge --no-ff <pr-branch>

(provide a sensible commit message, preferably including the username of the contributor)

$ git push
```

Wondering if that last line should have been ```git push origin master```?  I think this is the default, but the PR remains open.

**Comment by matthewmorgan** [comment]
OK, I think I got it.  I used GitHub's CLI instructions, which worked.  I still think it might be that last line.

**Comment by rchavarria** [comment]
What's the difference between Github's instructions and your comment? To avoid having the same problem as you.

**Comment by matthewmorgan** [comment]
First of all, I should say that I barely understand what is happening here.  Having said that, I think this is the gist of it:

Github's instructions (I think) create the same commit history that using the Big Green Button does, which is what I was trying to avoid.  I'll include them at the end of this comment.

My motivation in using the CLI was to avoid overlapping merge history by bringing the PR branches up to date with master before merging.  I think this will not be possible because it requires write access to the contributors' forks.  Ideally after the rebase we would push the changes to the contributor's branch, updating the commit history on the PR, and the rebased changes could be merged.

GitHub essentially recommends a ```merge``` without ```rebase```.

```
git checkout -b <username-pr-branch> master
git pull <username> <pr-branch>
Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff <username-pr-branch>
git push origin master
```

**Comment by kytrinyx** [comment]
> Step 2: Merge the changes and update on GitHub.

There's no need to update on GitHub.

Here's what I usually do:

First, make sure that my master is exactly what is on the GitHub master:

```
git checkout master && git fetch origin && git reset --hard origin/master
```

Next, fetch down the PR, and check it out to a new branch:

```
git fetch origin refs/pull/PR_NUMBER/head
get checkout -b pr-branch FETCH_HEAD
```

Then make sure that the PR is up to date with master, which removes any weird merge commits that they may have made by pulling from upstream instead of rebasing from upstream:

```
git rebase master
```

At this point I squash commits or make any edits that I want and amend the most recent commit.

Finally, switch to master, merge without fast forward (so that you get a merge commit), and give it a commit message (usually _merge pull request #XYZ from username/branch_).

Then push it up to master.

You don't need to edit the other person's branch. This method will usually not close the pull request unless you put a "Fixes" or "Closes" comment in the merge commit message, in which case you should close it manually with a note about the SHA1 of the merge commit (which links the PR to the code, even though you didn't push the green button).

If you haven't gotten your head wrapped around git, then I highly recommend the video of the conference talk [Git for Ages 4 and Up](https://www.youtube.com/watch?v=1ffBJ4sVUb4).

**Comment by matthewmorgan** [comment]
Thanks this is helpful.

Is there any way to have the PR show as 'merged' in the GUI?  Or just
'closed'?

**Comment by kytrinyx** [comment]
Just 'closed', unfortunately. As long as it has a link to the commit that closed it, I think that's perfectly fine.

**Comment by matthewmorgan** [comment]
OK thanks.


On Thu, Nov 12, 2015 at 5:22 PM, Katrina Owen <notifications@github.com>
wrote:

> Just 'closed', unfortunately. As long as it has a link to the commit that
> closed it, I think that's perfectly fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/xecmascript/pull/62#issuecomment-156255275>.
>



-- 
Matt Morgan
Director of Technology
Dulcet Software LLC
(734) 926-8142

**Pull request merged**
