### PR TITLE
Sync config.json with JS track

### PR DESCRIPTION
**Pull request by matthewmorgan**
@rchavarria I think if we merge another PR before this one,  this one will graph like your recent PRs that I merged IE skipping over one or more commits.

### CODE REVIEW

**Comment by rchavarria** [comment]
:cry: It didn't work. I followed the process. After `git rebase master`, a new commit was created (I think this is how git works, the commit parent changed, so the commit is given a new hash). I've tried to tell git that the commit to merge in the PR has changed with `git push -f origin sync-config` (`sync-config` was the branch name I gave to the PR). 

Instead of updating the remote branch, the one that created the PR, a new branch is created, with the new commit (the latest blue one). And your original branch was not modified (the last red one, still owned by you).

closed-not-merged

This process doesn't work to rebase PR that are not created from branches outside the main repo. Even worse, now, there is a new branch called `sync-config` that is shown in the graph as part of the main repo, and this branch is completely different from the one that originated this PR.

**Comment by kytrinyx** [comment]
You pushed a branch to the remote `origin`, so this is the expected behavior. If Matthew had pushed `-f` to his branch, then the pull request would have been updated.

A pull request is not a branch.

If you run `git ls-remote origin` you can see that a pull request is a different kind of reference (one that GitHub made up).

```
$ git ls-remote origin
dd502b6ff2f71e1c2bb461315cc3203dbcc85b81        HEAD
dd502b6ff2f71e1c2bb461315cc3203dbcc85b81        refs/heads/master
e7ee5885583809ea0631eff96826c07d7f153553        refs/heads/sync-config
abb6bc5ce8e4f2a56fffcf5c7a6a5568c5041585        refs/pull/101/head
70db123fbb59f7f957620ca0cc745645d665c8b6        refs/pull/104/head
1fdf61c11966ad0b8cab6f1eafbc00bb619c931e        refs/pull/106/head
46f1d59c1119d16786de2a6d3769dbb9ee25d27e        refs/pull/106/merge
````

You can delete the remote branch by saying:

```
git push origin :sync-config
```

I wrote a blog post a while back that talks about why the syntax looks like that: https://splice.com/blog/cleaning-git-branches/

**Comment by rchavarria** [comment]
Ok, thanks for the reference. I'll read it, looks really interesting.

@matthewmorgan and me are discovering more about git. If a user creates PR from branches in the main repo, other user (with write access to the main repo) can rebase it and update the branch (it updates the PR and it's shown as merged, even if rebase changes the commit).

But, if a user creates a PR from its forked repo, other users usually don't have rights to update the branch corresponding to the PR. So, the PR is shown as closed. It should be the first user who has to rebase the branch and update the PR in order to have it shown as merged.

Sorry, all messages are spread among several PRs. Just as reference, you can follow our experiments following PRs #149, #147 and #151

**Comment by matthewmorgan** [comment]
@kytrinyx @rchavarria thanks for the info.  I just deleted the branch using the 'delete branch' button above, and now the `sync-config` branch on my github fork is gone.

It also disappeared from the network graph of the exercism/xecmascript repo.  

I think this is the approach to take to keep things tidy if merging from contributors' forks.

**Pull request closed without merging**
