### PR TITLE
Move exercises into subdirectory, modify makefile accordingly

### PR DESCRIPTION
**Pull request by matthewmorgan**
As described in #187.

For some reason I don't understand, `gulpfile.js` and `package.json` are getting copied into the root `exercises/` directory.  Guessing that the `find` in the makefile is returning an empty result along with the exercise names?

Otherwise I think this is what you asked for @kytrinyx

### CODE REVIEW

**Comment by kytrinyx** [comment]
Yepp, this looks right. Merge when you both are happy with it.

**Comment by matthewmorgan** [comment]
@rchavarria let me know what you think.  If you have any ideas on how to prevent the extra copies of `gulpfile.js` and `package.json` I would be happy to modify the PR.

**Comment by rchavarria** [comment]
Interesting. I run the `make` command on an Ubuntu machine, and those files are not copied.

On line 32, try to replace: 

 ```
@for assignment in $(ASSIGNMENTS); do ASSIGNMENT=$$assignment $(MAKE) -s test-assignment || exit 1; done
```
with:
 ```
@for assignment in $(ASSIGNMENTS); do echo $$assignment; done
```
in order to see each value of `ASSIGNMENTS` variable.

**Comment by matthewmorgan** [comment]
I must have done something in the process of working on the PR to create those files.  I removed them, ran `make` again, and they are not reappearing.

**Comment by matthewmorgan** [comment]
I'm not sure what the conflicts are...I just fetched master and merged this branch onto it locally with no issues.

I can resolve it if you like.  Let me know.

**Comment by rchavarria** [comment]
You can even merge this PR.

Before merging it. Can you take a look at `palindrome-products` exercise? It seems a `.js` file has been removed. That file served as help. Now, if a user gets to the point of implementing that exersice, she'll be profient enough to create that on her own. But... I don' know, I wouldn't delete it (sorry, I don't have a stronger argument).

**Comment by matthewmorgan** [comment]
Oops...I thought that was my mistake.  I'll put `palindrome-products.js` back!

**Comment by rchavarria** [comment]
Thanks! Great job!

**Comment by kytrinyx** [comment]
w00t :)

**Pull request merged**
