### PR TITLE
new exercise scrabble-score

### PR DESCRIPTION
**Pull request by matthewmorgan**
added new exercise @rchavarria look OK?

### CODE REVIEW

**Comment by rchavarria** [comment]
Would you mind to add the `gulpfile.js` file, please?

You would probably have to rebase the branch because I merged other PR and `config.json` file has a conflict. I would resolve that conflict, but as `gulpfile.js` is missing, I prefer letting you to do the perfect PR.

**Comment by matthewmorgan** [comment]
That was painful.  I was unable to fix the conflicts without force-pushing to my fork/master, then recreating the branch and force-pushing the changes.  I wonder what I was doing wrong?

**Comment by rchavarria** [comment]
Sorry :cry: I didn't think it was going to be so painful. I thought it was going to be a small conflict in `config.json`. I have to admit that I have difficult times with `rebase` and conflicts.

**Comment by matthewmorgan** [comment]
No worries-- I definitely learned something new!  I think maybe the issue was that my fork/master was not current with exercism/master, so that even when I rebased my fork/PR-branch it was still complaining.

I have no doubt I will get another chance to find out... ;)

**Comment by matthewmorgan** [comment]
Thanks-- can I ask how you merged this PR?  It is showing up as 'merged'.

**Comment by kytrinyx** [comment]
I have an alias in my shell config file that makes it very easy to make sure that my master is up to date with origin:

```
alias remaster="git checkout master && git fetch origin && git reset --hard origin/master"
```

Though in your case if you're still using your fork, you would probably need to use `upstream` instead of origin.

**Comment by rchavarria** [comment]
I know. But I just followed the same process I used to merge the last 4 PRs.

Two of the last 4 PRs are shown as *Merged* and two as *Closed*. I merged the *Merged* ones in a machine I don't usually use it for personal projects (I use it from time to time). I merged the *Closed* ones in the machine when I usually work on side projects. Could it be related to some git configuration?

I've copied one configuration, and when I have time, I'll compare both configurations to know if there is any difference.

**Comment by kytrinyx** [comment]
The difference could be whether or not the branch was rebased onto master, but I really don't know. I would have to experiment a bit.

**Comment by rchavarria** [comment]
@kytrinyx Nope. I've cloned exercism/xecmascript repo locally (btw, I don't know if that is a good or a bad practice). I plan to use it only for merging PRs.

And thanks for the alias. That's exactly how I started all PR merges.

**Comment by kytrinyx** [comment]
Yeah, it's perfectly good to clone exercism/xecmascript locally. If you want to do PRs, then pushing up branches is the simplest and cleanest way. I don't see any reason to use a fork when you have commit on the project.

**Comment by matthewmorgan** [comment]
@kytrinyx @rchavarria thanks!

**Comment by rchavarria** [comment]
I don't know if the reason could be this: today, while merging some @matthewmorgan's PRs, I've noticed that `git fetch origin` downloads PRs as branches (kind of, at least references to those PRs as branches). I'm not sure what I did other times, but this time I've seen several *new branches* and it worked for PR #74

**Comment by kytrinyx** [comment]
Interesting!

**Pull request merged**
