### PR TITLE
New exercise: Space age

### PR DESCRIPTION
**Pull request by rchavarria**
There we go! Another exercise.

### CODE REVIEW

**Comment by kytrinyx** [comment]
What happened to this one?

**Comment by rchavarria** [comment]
Oops!! I made a mistake while playing locally with the repo (rebasing,...). Then, I pushed my local changes and broke my repo on github :cry:

I wasn't sure how to fix it, so I decided to start from scratch. I deleted my github repo, and cloned again from exercism/xecmascript. It seems I broke more things than my local and github repo.

is exercism/xecmascript repo ok? I hope so. I hope it's only this pull request what is wrong.

**Comment by kytrinyx** [comment]
Yeah, exercism/xecmascript is fine :)

If you have time, check out this video: https://www.youtube.com/watch?v=1ffBJ4sVUb4 Git Ages 4 and Up

**Comment by rchavarria** [comment]
*4 and up*? :joy: I think I can do it. Thanks for the video!!

**Comment by kytrinyx** [comment]
LOL, yeah, I know. The quality of the video/sound is not great, but the content is phenomenal.

**Pull request closed without merging**
