### PR TITLE
new exercise clock

### PR DESCRIPTION
**Pull request by matthewmorgan**
added new exercise clock

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@rchavarria would you mind checking this out and merging if it looks OK?  Thanks!

**Comment by rchavarria** [comment]
Thanks! This is an interesting exercise.

**Comment by rchavarria** [comment]
I don't understand. I followed the same process as #67 but the PR appears as *Closed* instead of *Merged*.

**Comment by kytrinyx** [comment]
I think it always shows as closed if you merge locally. That's always been my experience, anyway.

**Pull request closed without merging**
