### PR TITLE
Add new exercise accumulate

### PR DESCRIPTION
**Pull request by matthewmorgan**
As described in #94

### CODE REVIEW

**Comment by rchavarria** [comment]
Only one left for tonight!
Great job @matthewmorgan!

**Comment by kytrinyx** [comment]
Killin' it! This is great.

**Comment by rchavarria** [comment]
@kytrinyx I love your encouraging phrases. The most imaginative I usually come up with is a plain *Thanks*. I think I need to build a list and I pick one at random.

**Comment by kytrinyx** [comment]
I'm sure there's a bot for that :)

I just get really excited to see so much activity in a track that has been practically orphaned for so long. The two of you have a really great rhythm going--good discussions and lots of really great work. It is lovely to see.

**Comment by rchavarria** [comment]
Yeah, I'm enjoying it a lot.

**Comment by matthewmorgan** [comment]
@kytrinyx I looked for a bot but didn't find it!

@rchavarria Thanks to both of you-- having fun and learning a lot.  👊

**Comment by kytrinyx** [comment]
:)

**Comment by rchavarria** [comment]
It's not exactly a bot, and it doesn't generate the most appropiate compliments for Github contributions, but it's fun: [ComplimentBot 4000](http://ourstereo.com/compliment/)

**Comment by kytrinyx** [comment]
Hah. _All your colleagues miss you when you call in sick._

**Pull request merged**
