### PR TITLE
Add new exercise hexadecimal

### PR DESCRIPTION
**Pull request by matthewmorgan**
As described in #126

### CODE REVIEW

**Comment by rchavarria** [comment]
What do you think if the last three test descriptions are changed to something similar to this?

```
xit('HTML/CSS represents <color> with hexadecimal value <hex-value>', () => { ... }
```

**Comment by matthewmorgan** [comment]
I was thinking the same thing, but had sort of enjoyed the 'puzzle' of figuring out the color reference when I originally did the exercise.  

Either way is fine with me.

**Comment by rchavarria** [comment]
I see. Maybe a less explicit description:

```
xit('hexadecimal value for HTML/CSS <white/black/yellow> color', () => { ... }
```

**Comment by matthewmorgan** [comment]
I think that's fine.  I'll make the change now.

**Comment by rchavarria** [comment]
Nice!!

**Pull request merged**
