### PR TITLE
Sync config.json with JS track

### PR DESCRIPTION
**Pull request by matthewmorgan**

### CODE REVIEW

**Comment by rchavarria** [comment]
`palindrome-products` is not my favourite exercise, but I wouldn't delete it :stuck_out_tongue_winking_eye: 

Has it been deleted by mistake?

**Comment by matthewmorgan** [comment]
@rchavarria it looks like the ES track and the JS track are more divergent than I thought.  There are several exercises from the JS track that have been skipped over, and palindrome-products should have been included far later than it was.  I'll make an audit of what's missing and put the exercises in as separate PRs.

**Comment by kytrinyx** [comment]
Check out the "todo" key:
- http://x.exercism.io/tracks/javascript
- http://x.exercism.io/tracks/ecmascript

I could write a quick script that would get the list of problems that are implemented in javascript but not ecmascript, and the reverse.

**Comment by rchavarria** [comment]
Does the `todo` key tell the defined exercises (in x-common I think) that are not yet implemented in the track?

That could be a better source of new exercises to add to the track.

**Comment by matthewmorgan** [comment]
There are a large number not yet implemented in the JS track too.

**Comment by kytrinyx** [comment]
Yeah, that's exactly what it says: exercises that are in x-common that are not in the `problems` list. It doesn't take the `foregone` and `deprecated` ones though.

**Comment by matthewmorgan** [comment]
@kytrinyx you offered a while back to compile the exercise list not yet implemented in the ES track-- can I impose on you to do that?  Time to add some new things!

**Comment by kytrinyx** [comment]
This is that list http://x.exercism.io/v3/tracks/ecmascript ... but I think we actually talked about figuring out what's in JavaScript that's not in ECMAScript, right?

**Comment by kytrinyx** [comment]
Currently everything that is implemented in JavaScript is also implemented in ECMAScript.

**Comment by matthewmorgan** [comment]
I was thinking about what to add next (to both tracks.)  I see that the
'todo' node in the JSON has unimplemented items.

Is anything on the 'to-do' list fair game?  Or is there some sort of
precedence on which to add first?

BTW I'm thinking at some point it might make sense to merge the JS and ES
tracks.  Seems like browser support is too uneven to do that yet.

On Fri, Jan 15, 2016 at 10:48 AM, Katrina Owen <notifications@github.com>
wrote:

> Currently everything that is implemented in JavaScript is also implemented
> in ECMAScript.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/xecmascript/pull/130#issuecomment-171996676>.
>



-- 
Matt Morgan
Director of Technology
Dulcet Software LLC
(734) 926-8142

**Comment by kytrinyx** [comment]
Anything there is fair game.

You can use http://x.exercism.io/problems/:slug (e.g. http://x.exercism.io/problems/clock) to see which tracks have implemented it, so you can go crib ideas from there.

Also, some of the tracks have a json file with inputs/outputs used in test suites over in the x-common directory (`:slug.json`).

**Comment by kytrinyx** [comment]
I added a ticket for a feature that would have been useful here: https://github.com/exercism/x-api/issues/94

**Pull request merged**
