### PR TITLE
Add new exercise say

### PR DESCRIPTION
**Pull request by matthewmorgan**
As described #152

### CODE REVIEW

**Comment by rchavarria** [comment]
Thanks for this one, it's fun.

Just asking an English question: shouldn't 142 be said as "one hundred **and** forty-two"?

And, I find it weird to export a `new Say()` object in `example.js` instead of just the `Say` class. What do you think?

**Comment by matthewmorgan** [comment]
As far as the english, it depends.  When talking about money, usually 'and' separates dollars from cents.  EG 'one hundred and forty-two' = 100.42 rather than 142.  Otherwise you are correct.

Exporting the new `Say()` was a pain!  I would much rather have exported a class, the implementation would be cleaner.  I think this sort of inconsistency is what we were discussing on xjavascript with https://github.com/exercism/xjavascript/issues/128.

I would be happy to change it, but it would not match JS.  What do you think?

**Comment by rchavarria** [comment]
I would just export the class. It doesn't matter too much if this track differs a little bit from xjavascript. 

Then, there is no a big change in the tests. Just add a new line saying `const say = new Say()` and all `it` blocks remain the same.

**Comment by matthewmorgan** [comment]
OK @rchavarria I changed the export structure.

**Comment by rchavarria** [comment]
Much nicer. Thank you so much!!

**Pull request merged**
