### PR TITLE
Add new exercise octal

### PR DESCRIPTION
**Pull request by matthewmorgan**
As described in #105

### CODE REVIEW

**Comment by rchavarria** [comment]
Thanks a lot for your contributions

**Comment by rchavarria** [comment]
I think now I really understand why some PRs are shown as *Merged* and others as *Closed*. Let's look at the latest merged PRs #104 and #106 (this one).

Before merging any of them, branches `new-exercise-simple-cipher` and `new-exercise-octal` had the `master` `HEAD` commit as their commits' parent:

simple-cipher-before-merging

Once #104 was merged, the commit on `new-exercise-octal` branch no longer has `master` `HEAD` as parent.

simple-cipher-after-merging

When `new-exercise-octal` branch is going to be merged, `git rebase master` needs to be executed, and a new commit with a different hash is created. Sometimes, there is a conflict and it makes sense to have a new commit created. But even if there is no conflict, `git rebase` creates a new commit with a different has so that Github (or git) does not detect the merged branch as really merged, because the merged commit is not the same commit as the one in the branch.

octal-after-merging

As you can see, the commit on `new-exercise-octal` is still in a separate branch. But there is a commit with the same message (resulting of `git rebase master`) that is merged into master.

**Comment by kytrinyx** [comment]
If the branches are on the same repo as master, then you can `git push -f origin BRANCH_NAME` to update the pull request, which will let you use the green button to merge.

**Comment by matthewmorgan** [comment]
Interesting.

What if you rebased master, cherry pick the new exercise commit from the new branch and force push to the new branch before merging?

**Comment by rchavarria** [comment]
@kytrinyx If a user creates a pull request, the branch in his repository is *converted* in a branch in the repository where the PR is created? If so, `git push -f` could be used.

**Comment by kytrinyx** [comment]
No, you can't push to a pull request, as far as I can tell.

**Comment by matthewmorgan** [comment]
I think you can pull down the new branch, ```git merge master```, fix the conflicts, and ```git push -f new-branch```.

**Comment by matthewmorgan** [comment]
Check out #93

**Comment by matthewmorgan** [comment]
Or maybe not...

**Comment by rchavarria** [comment]
Not sure. But I think it has worked on merging #101 

After `git rebase master` there was a conflict in `config.json`. I fixed the conflict, continue the rebase and `git push -f origin <pr-branch>`.

Then, `git checkout master` and `git merge --no-ff`. :tada: Magic! PR is *Merged* instead of *Closed*.

I need to do it again to be sure.

**Comment by kytrinyx** [comment]
Niiice!

**Pull request closed without merging**
