### PR TITLE
Only one test should be active

### PR DESCRIPTION
**Pull request by rchavarria**
2 out of 3 tests are active. Only the first one is active now.

### CODE REVIEW

**Comment by rchavarria** [comment]
Sorry. I didn't realize there were more than one commit. Closed.

**Comment by kytrinyx** [comment]
You can also rebase onto master and squash commits. Rebasing usually gets rid of merge commits. Let me know if you want me to point you to resources about any of that.

**Comment by rchavarria** [comment]
I know the basics about rebasing. I'm able to rebase the latest commits. I've done it in some pull requests.

I've read they are dangerous if commits have been pushed to the remote repo. And I think they will be even more dangerous if a third party have pulled those commits locally.

What would happen if I rebase locally those commits, then push them to exercism/xecmascript (forcing the push, or they will be rejected)? Will you be able to pull the right repo history from exercism/xecmascript? 

I already messed up my repo, I don't want to do it with the exercism one. I'd appreciate any resource, I'm here for learning :wink: 

Let's say I rebase these commits. Should I work on exercism repo? Or would it be better to work on my repo and create a pull request?

**Comment by kytrinyx** [comment]
You should not rebase master, but if you rebase in your own repo, or on a branch before it's merged, that's fine.

**Comment by rchavarria** [comment]
Yep. That's what I thought. And you're right, in this case, I could have rebased my initial pull request to squash additional commits. I don't know why I didn't realize that.

Anyway, a PR with the same changes I wanted to contribute with this PR has been merged, so we can forget about this one.

**Comment by kytrinyx** [comment]
Ok cool!

**Pull request closed without merging**
