### PR TITLE
Add eslint

### PR DESCRIPTION
**Pull request by matthewmorgan**
@rchavarria is this what you had in mind for #44 ?

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@rchavarria It looks like perhaps the last merge resulted in some conflicts on this PR.  I will fix as soon as I can and ping you.

**Comment by matthewmorgan** [comment]
@rchavarria should be set.  See what you think.  Thanks!

**Comment by rchavarria** [comment]
About `config.json`. Right now, I can think of a workaround, and it's to edit different lines in different pull rquests. But I'm not sure it that would work. Later, in other PR we could reorganize all exercises to match the same order as xjavascript.

About ESLint. Thanks! That is exactly what I had in mind. I was planning to use a `.eslintrc` file to configure it, and to lint much more aspects of the JavaScript code. But this PR is the perfect starting point.

I would merge it, but it would cause a problem to exercism users trying to solve the exercises. The new `gulpfile.js` needs a new dependency, `gulp-eslint`. That dependency is only added to the `package.json` file in the root directory, and it should be added to every `package.json` of every individual exercise. Otherwise, users won't be able to run tests. The `gulp test` command will fail.

*Note: I'm not sure, but I think I tried to copy `package.json` as it's done with `gulpfile.js` but it didn't work. You probably need to edit each `package.json` file manually* :cry:

This made two problems arise:

1. Files `gulpfile.js`, `package.json` and `.eslintrc` (if we decide to use it in the future) are duplicated (or kind of) in every single exercise. @kytrinyx, is there a way to include those files when exercism users fetch an exercise to avoid having them copied on each exercise folder?
2. Running tests with `make` (at development time) and running tests as an exercism user are not the same process. It seems, all exercises share the same `npm` installation when running it with `make`. That's why the `make` command does not fail, but running tests as a user fails.

**Comment by matthewmorgan** [comment]
@rchavarria Hmm... I tested some individual exercises using ```gulp test``` from within the exercise directories.  Must be it worked bc of the ```npm install``` for the xecmascript directory above it.

If I understand you correctly, changing all the ```package.json``` files in the individual exercises would fix things for now?  I could do that if @kytrinyx says it is complicated to fetch the global ```package.json``` file.

Also, I did intially set this up using ```.eslintrc``` in the global directory, but it seemed to be redundant with the option hash in the gulpfile.

Anyway, I'm happy to modify the individual ```package.json``` files for now-- just let me know.  Thanks!

**Comment by rchavarria** [comment]
Yep, go for modifying individual `package.json` files please.

We can address other tasks in different issues/PRs: improving lint process, *duplicated* files and npm installations.

**Comment by matthewmorgan** [comment]
@rchavarria there you go.  Thanks for catching that issue!

**Comment by matthewmorgan** [comment]
@rchavarria I can merge this if you like. 😃  I think I made the changes as you requested.

**Comment by rchavarria** [comment]
I looks totally fine now, thanks for the effort!!

**Pull request merged**
