### PR TITLE
Add new exercise crypto-square

### PR DESCRIPTION
**Pull request by matthewmorgan**
Add described in #96

### CODE REVIEW

**Comment by rchavarria** [comment]
Thanks @matthewmorgan, you rocks!

**Comment by rchavarria** [comment]
Yeah! Followed the additional process discussed on #106, `git push -f origin new-exercise-crypto-square` works like a charm and PRs are shown as *Merged*.

**Comment by matthewmorgan** [comment]
Right on.  Good work.  Now I'll have enough Merge points to level up!

**Comment by kytrinyx** [comment]
Sweeeeet!

**Pull request merged**
