### PR TITLE
Add new exercise: Pascal's triangle

### PR DESCRIPTION
**Pull request by rchavarria**
As described in #150

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@rchavarria well done again.  In this, I think you can use `const` instead of `let` for `result` if you want.  No big deal of course!

**Comment by rchavarria** [comment]
Same as #149, whatever we decide there.

**Comment by matthewmorgan** [comment]
Yes, I think you can try merging these if you want-- try our experiment on the graph!

**Comment by rchavarria** [comment]
#147 didn't work. And this PR had some conflicts I had to fix. Now, this PR is on master's HEAD, so there is no point to merge it if we want to learn how to merge several PR with the same commit as parent. So, I'll wait until we have more PR.

Then, I think I'll try a new approach:

```
git checkout master
git fetch origin master
git reset --hard origin/master
git fetch origin refs/pull/<pr>/head
git checkout -b <pr-branch> FETCH_HEAD
```

Now, I'll try to create a branch in the remote repo, that contains the commit of the PR.

```
git push origin <pr-branch>
```

And continue as always:

```
git rebase master
## if commit changes, I'll update remote branch
git push -f origin <pr-branch>
git checkout master
git merge --no-ff <pr-branch>
git push origin master
```

If it doesn't work, the best option is to create PR from the main repository in our local machine. When all exercises are added, and there is much less work, we can continue working from our forks, bit by bit, and rebasing in our forks and updating the PRs.

**Comment by matthewmorgan** [comment]
@rchavarria after reviewing the discussion on #147 it sounds like we have two options:
1) Work with the main repo, branching to add features and create PRs.
2) Continue to work with forks, but delete the fork afterward.

I would favor #1 for anyone who has write access, #2 as a fallback.  What do you think?

**Comment by rchavarria** [comment]
I would say option 1) for anyone with write access *and* multiple PR in a sort period of time (to avoid rebasing in a fork). But, as a rule of thumb, just anyone with write access. The most important point is to work with branches.

**Pull request merged**
