### PR TITLE
Add new exercise: Kindergarten garden

### PR DESCRIPTION
**Pull request by rchavarria**
A new exercise ported form xjavascript

### CODE REVIEW

**Comment by rchavarria** [comment]
Whoops. Travis CI fails. If works when I originally push this branch in my [xecmascript fork](https://travis-ci.org/rchavarria/xecmascript/builds/95076902). It seems something changed:

travis-change

> This job run on our new platform for Legacy Precise builds...

@kytrinyx Are other tracks having issues with Travis CI?

**Comment by kytrinyx** [comment]
Not that I know of. The failure was:

```
0.02s$ make test
make[1]: npm: Command not found
make[1]: *** [node_modules] Error 127
make: *** [test] Error 1
The command "make test" exited with 2.
```

which seems like a transient failure. I've restarted the build.

**Comment by kytrinyx** [comment]
It's failing on two different PRs. I have no idea what's going on. It would be worth jumping in the travis-ci IRC room and asking if there's a way to figure out if we're doing something wrong.

I'm traveling today and tomorrow and probably won't have time do this, but if you have time to ask them, go for it!

**Comment by matthewmorgan** [comment]
Is this something that we might be able to fix by modifying the `.travis.yml` file?

**Comment by kytrinyx** [comment]
That's the thing--maybe. But we didn't change the .travis.yml file, and it started failing. We should (in any case) say `sudo: false` to use the container-based builds, but I doubt that this has anything to do with anything.

**Comment by matthewmorgan** [comment]
Thanks @rchavarria!  Your coworkers miss you when you call in sick.

**Comment by rchavarria** [comment]
LOL!

**Pull request merged**
