### PR TITLE
Fix test to require deep copy

### PR DESCRIPTION
**Pull request by StevenACoffman**

### CODE REVIEW

**Comment by rchavarria** [comment]
Thanks for catching it. It seems to me the test is testing two things: client code can't add new levels to the `roster` array, and client code can't add students to an existing level (forcing `roster()` method to return a deep copy of the internal `roster`).

What do you think of splitting the current test, `roster cannot be modified outside of module` into:

- `new levels can not be added to roster`
- `new students can not be added to existing levels`

**Comment by StevenACoffman** [comment]
I think in general that both unit test readability and maintainability are reduced by having multiple tests for the same simple behavior. The behavior you are trying to test for is that it is not possible to change the internal state externally, except using the exposed methods. I question how it likely any solution that prevented new students from being externally added to existing levels would still allow new levels to be externally added to the roster, so I think it would be fair to remove the line:

```javascript
roster[3] = ['Oops.'];
```

But it's relatively harmless (i.e. does not overly reduce readability or add to maintenance burden) to leave it as well. Honestly, I'm just doing these exercises for personal fun, so it's not a big deal to me. This is just my mild opinion.

**Comment by rchavarria** [comment]
Yep, I'm also here for fun, and for learning, and it's neither a big deal for me. I just wanted to have a constructive *discussion* in order to learn. I'm sorry if I didn't express myself right, English is not my mother tongue and I think sometimes I sound too rude.

I also consider removing that line:

```
roster[3] = [ 'Oops.' ];
```

And I see your point about it. So, for me it would be also ok to keep just one test, remove `roster[3]...` and replace it with `roster[2].push(...)`.

**Comment by matthewmorgan** [comment]
@StevenACoffman @rchavarria  I agree with your conclusions.  ```Object.seal``, ```Object.freeze``` and ```Object.preventExtensions``` wouldn't allow the addition of new grades in this exercise.  In some cases you would be able to modify the student list, but not the other way around.

I would be happy to merge this, I think we're waiting on 53 first.

**Comment by matthewmorgan** [comment]
@rchavarria also, do we need this change on its own branch?  Looks like right now it's on master.

**Comment by StevenACoffman** [comment]
@rchavarria I thought you were perfectly polite and quite nice. I just wanted to clarify that I don't have strong opinions on this.
@matthewmorgan I'm not sure what the project contribution convention is. Do the work on a topic/issue branch (branch naming conventions?), and squash (rebase) all the commits? I hadn't anticipated there would be multiple commits, nor seen any example branches. I can close this PR and do it again if that's cleaner.

**Comment by matthewmorgan** [comment]
Hey Steve,
In fairly new at this, but my understanding is that the convention is to create a new branch and generate the pull request on that branch, using one commit, squashing if required.
I don't know if it is possible to change the pr to a dedicated branch at this point, it might make more sense to close it.  I am unclear on what the implications of having your changes directly on the master branch are, but it doesn't seem to be the way here.
Here's a link to the contributing guide 
https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md

Matt Morgan




On Mon, Nov 9, 2015 at 6:50 AM -0800, "Steve Coffman" <notifications@github.com> wrote:












@rchavarria I thought you were perfectly polite and quite nice. I just wanted to clarify that I don't have strong opinions on this.

@matthewmorgan I'm not sure what the project contribution convention is. Do the work on a topic/issue branch (branch naming conventions?), and squash (rebase) all the commits? I hadn't anticipated there would be multiple commits, nor seen any example branches. I can close this PR and do it again if that's cleaner.

**Comment by StevenACoffman** [comment]
Closing to try it on a branch.

**Comment by rchavarria** [comment]
:+1: @matthewmorgan explained it perfectly, it's preferred to work on a separate branch (I think there is no naming conventions) and then merge onto master.

Thanks @StevenACoffman and @matthewmorgan for this conversation.

**Pull request closed without merging**
