### PR TITLE
Add new exercise: Nth prime

### PR DESCRIPTION
**Pull request by rchavarria**
As described in #148

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@rchavarria looks good to me.  Only thing I saw was the `possiblePrimes` could be `const` I believe.  Could be merged now, or make that one change if you like.

**Comment by rchavarria** [comment]
I'll do the change.

**Comment by rchavarria** [comment]
Looking at the code, I prefer to keep it as `let`. Technically, it can be `const` and there won't be an error. But as `possiblePrimes` is a variable that changes its value (new primes are added to the list), `let` seems more appropriate.

I remember I had a conversation about this with an exercism user, and I liked a lot his reasons: if it's a variable that changes its value (i.e.: a list where elements are added), `let` seems a better option.

**Comment by matthewmorgan** [comment]
Yes, for objects the reference is the 'constant' bit rather than the value.  I don't have any issue with it myself!

**Comment by rchavarria** [comment]
Ok, first PR merged. This is the easiest one.

**Pull request merged**
