### PR TITLE
gulpfile uses const instead of var

### PR DESCRIPTION
**Pull request by matthewmorgan**
one more change to the gulpfile to make it a little more ES6-y.  @rchavarria let me know if this looks OK.  Thanks!

### CODE REVIEW

**Comment by rchavarria** [comment]
I agree with the change.

There is a little thing. When you run the command `make`, to run all tests, the script copies the `gulpfile.js` file in the root directory to every exercise directory. Would you mind to run `make` and add those changes to the PR?

If you can't run `make` I can do it for you. There is no problem.

**Comment by matthewmorgan** [comment]
@rchavarria should be all set.

**Comment by rchavarria** [comment]
Thanks for all the work. Nice!

Again, it appears as *Closed*. I don't get it yet.

**Comment by matthewmorgan** [comment]
I was having the same problem earlier...I couldn't figure it out.  The only way I could get the PR to show as 'merged' was by using the Big Green Button.

**Pull request closed without merging**
